<?php

namespace App\Models;

use App\Enums\IncidentOutcome;
use App\Enums\RequestStatus;
use App\Enums\SosReason;
use App\Enums\UrgencyLevel;
use App\Enums\VerificationStatus;
use App\Models\Concerns\Auditable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Validation\ValidationException;

class EmergencyRequest extends Model
{
    use Auditable;

    protected $fillable = [
        'resident_id',
        'description',
        'source',
        'sos_channel',
        'sos_reason',
        'sos_reason_other',
        'device_id',
        'reporter_verification_status',
        'category',
        'category_confidence',
        'urgency',
        'urgency_confidence',
        'needs_review',
        'review_reason',
        'validated_at',
        'validated_by',
        'latitude',
        'longitude',
        'location_accuracy_meters',
        'location_flags',
        'attachment_path',
        'status',
        'outcome',
        'outcome_set_by',
        'outcome_set_at',
    ];

    /** GPS accuracy worse than the configured threshold. */
    public const FLAG_POOR_ACCURACY = 'poor_accuracy';

    /** The device did not report an accuracy value at all. */
    public const FLAG_ACCURACY_UNKNOWN = 'accuracy_unknown';

    /** Coordinates fall outside the configured barangay radius. */
    public const FLAG_OUTSIDE_BOUNDS = 'outside_bounds';

    protected function casts(): array
    {
        return [
            'category_confidence' => 'decimal:4',
            'urgency_confidence' => 'decimal:4',
            'urgency' => UrgencyLevel::class,
            'status' => RequestStatus::class,
            'needs_review' => 'boolean',
            'validated_at' => 'datetime',
            'latitude' => 'decimal:7',
            'longitude' => 'decimal:7',
            'location_accuracy_meters' => 'decimal:2',
            'location_flags' => 'array',
            'sos_reason' => SosReason::class,
            'reporter_verification_status' => VerificationStatus::class,
            'outcome' => IncidentOutcome::class,
            'outcome_set_at' => 'datetime',
        ];
    }

    public function resident()
    {
        return $this->belongsTo(User::class, 'resident_id');
    }

    public function validator()
    {
        return $this->belongsTo(User::class, 'validated_by');
    }

    public function outcomeSetter()
    {
        return $this->belongsTo(User::class, 'outcome_set_by');
    }

    public function statusLogs()
    {
        return $this->hasMany(RequestStatusLog::class)->orderBy('created_at');
    }

    public function assignments()
    {
        return $this->hasMany(ResponseAssignment::class);
    }

    public function currentAssignment()
    {
        // Do not use latestOfMany() here. The service layer intentionally
        // applies FOR UPDATE when changing assignments, and PostgreSQL rejects
        // row locking on the GROUP BY query generated by latestOfMany(). A
        // deterministic ordered has-one query is lock-compatible and still
        // returns the newest active assignment when bad historical data leaves
        // more than one active row.
        return $this->hasOne(ResponseAssignment::class)
            ->whereNull('completed_at')
            ->orderByDesc('id');
    }

    public function classificationLogs()
    {
        return $this->hasMany(TokenizationClassificationLog::class);
    }

    public function outboundSmsMessages()
    {
        return $this->hasMany(OutboundSmsMessage::class);
    }

    /**
     * Feature 2: raised from the SOS button rather than the report form.
     */
    public function isSos(): bool
    {
        return in_array($this->source, ['sos', 'sms_fallback'], true);
    }

    /**
     * Feature 2: the reason as shown to responders, including the resident's
     * own words when they chose "Other".
     */
    public function sosReasonLabel(): ?string
    {
        if ($this->sos_reason === null) {
            return null;
        }

        return $this->sos_reason === SosReason::Other && filled($this->sos_reason_other)
            ? sprintf('Other: %s', $this->sos_reason_other)
            : $this->sos_reason->label();
    }

    /**
     * Feature 2: who may record an outcome or clear the reporter's cooldown —
     * any official or administrator, or a responder who was assigned to this
     * incident at any point (the assignment is closed once it is resolved).
     */
    public function isHandledBy(User $user): bool
    {
        if ($user->isOfficialOrAdmin()) {
            return true;
        }

        return $user->isPersonnel()
            && $this->assignments()
                ->whereHas('responsePersonnel', fn ($personnel) => $personnel->where('user_id', $user->id))
                ->exists();
    }

    /**
     * Feature 2: an outcome may be recorded only once the response is over.
     */
    public function canRecordOutcome(): bool
    {
        return in_array($this->status, [RequestStatus::Resolved, RequestStatus::Cancelled], true);
    }

    /**
     * Determine whether the request can move from its current status to the
     * requested status. This keeps the emergency-response lifecycle ordered
     * and prevents reopening completed/cancelled requests.
     */
    public function canTransitionTo(RequestStatus $status): bool
    {
        $allowedTransitions = [
            RequestStatus::Submitted->value => [
                RequestStatus::NeedsReview,
                RequestStatus::Validated,
                RequestStatus::Cancelled,
            ],
            RequestStatus::NeedsReview->value => [
                RequestStatus::Validated,
                RequestStatus::Cancelled,
            ],
            RequestStatus::Validated->value => [
                RequestStatus::Assigned,
                RequestStatus::Cancelled,
            ],
            RequestStatus::Assigned->value => [
                RequestStatus::EnRoute,
                RequestStatus::Resolved,
                RequestStatus::Cancelled,
            ],
            RequestStatus::EnRoute->value => [
                RequestStatus::Resolved,
                RequestStatus::Cancelled,
            ],
            RequestStatus::Resolved->value => [],
            RequestStatus::Cancelled->value => [],
        ];

        return in_array($status, $allowedTransitions[$this->status->value] ?? [], true);
    }

    /**
     * Record a status change and append it to the tracking timeline
     * (Feature 7: Real-Time Urgent Status Tracking).
     */
    public function transitionTo(RequestStatus $status, ?string $note = null, ?int $changedBy = null): void
    {
        if (! $this->canTransitionTo($status)) {
            throw ValidationException::withMessages([
                'status' => sprintf(
                    'Request cannot transition from %s to %s.',
                    $this->status->label(),
                    $status->label()
                ),
            ]);
        }

        $attributes = ['status' => $status];

        // Validation is a lifecycle event, not only a status label. Keep the
        // audit fields synchronized and clear the review flag once an official
        // or trusted automated path validates the request.
        if ($status === RequestStatus::Validated) {
            $attributes += [
                'needs_review' => false,
                'review_reason' => null,
                'validated_at' => now(),
                'validated_by' => $changedBy,
            ];
        }

        $this->update($attributes);
        $this->statusLogs()->create([
            'status' => $status->value,
            'note' => $note,
            'changed_by' => $changedBy,
        ]);
    }
}
